---@class Chocolatier
---@field config ChocolatierConfig
---@field palette ChocolatierPalette

local Chocolatier = {}

---@alias Contrast "hard" | "soft" | ""

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class ChocolatierConfig
---@field terminal_colors boolean?
---@field undercurl boolean?
---@field underline boolean?
---@field bold boolean?
---@field italic ItalicConfig?
---@field strikethrough boolean?
---@field contrast Contrast?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field invert_intend_guides boolean?
---@field inverse boolean?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?

Chocolatier.config = {
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true,
  contrast = "",
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}

-- main chocolatier color palette
---@class ChocolatierPalette
Chocolatier.palette = {
  -- BACKGROUND
  dark0 = "#281f11",
  dark0_soft = "#281f11",
  dark0_hard = "#281f11",
  dark1 = "#4e3819",
  dark2 = "#644c2c",
  dark3 = "#7c5f35",
  dark4 = "#8a693c",

  -- FOREGROUND
  light0 = "#ebc295",
  light0_soft = "#ebc295",
  light0_hard = "#ebc295",
  light1 = "#d3af86",
  light2 = "#c5a37d",
  light3 = "#aa8c6b",
  light4 = "#907659",

  -- ORANGE
  bright_orange = "#f79a32",
  neutral_orange = "#f79a32",
  faded_orange = "#f79a32",
  light_orange = "#f79a32",
  light_orange_soft = "#f79a32",
  light_orange_hard = "#f79a32",
  dark_orange = "#a96920",
  dark_orange_soft = "#a96920",
  dark_orange_hard = "#a96920",

  -- RED
  bright_red = "#c33a2b",
  neutral_red = "#c33a2b",
  faded_red = "#c33a2b",
  light_red = "#c33a2b",
  light_red_soft = "#c33a2b",
  light_red_hard = "#c33a2b",
  dark_red = "#9d2f23",
  dark_red_soft = "#9d2f23",
  dark_red_hard = "#9d2f23",

  -- GREEN
  bright_green = "#889b4a",
  neutral_green = "#889b4a",
  faded_green = "#889b4a",
  light_green = "#889b4a",
  light_green_soft = "#889b4a",
  light_green_hard = "#889b4a",
  dark_green = "#657829",
  dark_green_soft = "#657829",
  dark_green_hard = "#657829",

  -- YELLOW
  bright_yellow = "#fbb53a",
  neutral_yellow = "#fbb53a",
  faded_yellow = "#fbb53a",
  light_yellow = "#fbb53a",
  light_yellow_soft = "#fbb53a",
  light_yellow_hard = "#fbb53a",
  dark_yellow = "#bb872b",
  dark_yellow_soft = "#bb872b",
  dark_yellow_hard = "#bb872b",

  -- BLUE
  bright_blue = "#83a598",
  neutral_blue = "#83a598",
  faded_blue = "#83a598",
  light_blue = "#83a598",
  light_blue_soft = "#83a598",
  light_blue_hard = "#83a598",
  dark_blue = "#458588",
  dark_blue_soft = "#458588",
  dark_blue_hard = "#458588",

  -- PURPLE
  bright_purple = "#bb7d81",
  neutral_purple = "#bb7d81",
  faded_purple = "#bb7d81",
  light_purple = "#bb7d81",
  light_purple_soft = "#bb7d81",
  light_purple_hard = "#bb7d81",
  dark_purple = "#7b5154",
  dark_purple_soft = "#7b5154",
  dark_purple_hard = "#7b5154",

  -- AQUA
  bright_aqua = "#8ec07c",
  neutral_aqua = "#8ec07c",
  faded_aqua = "#8ec07c",
  light_aqua = "#8ec07c",
  light_aqua_soft = "#8ec07c",
  light_aqua_hard = "#8ec07c",
  dark_aqua = "#689d6a",
  dark_aqua_soft = "#689d6a",
  dark_aqua_hard = "#689d6a",

  -- FUSCIA
  bright_fuscia = "#db4664",
  neutral_fuscia = "#db4664",
  faded_fuscia = "#db4664",
  light_fuscia = "#db4664",
  light_fuscia_soft = "#db4664",
  light_fuscia_hard = "#db4664",
  dark_fuscia = "#a92b43",
  dark_fuscia_soft = "#a92b43",
  dark_fuscia_hard = "#a92b43",

  alt_g = "#928374",
  alt_a = "#251d18",
  alt_b = "#30211c",
  alt_h = "#221a0f",
  alt_r = "#1E170D",
  alt_s = "#372a16",
}

-- get a hex list of chocolatier colors based on current bg and constrast config
local function get_colors()
  local p = Chocolatier.palette
  local config = Chocolatier.config

  for color, hex in pairs(config.palette_overrides) do
    p[color] = hex
  end

  local bg = vim.o.background
  local contrast = config.contrast

  local color_groups = {
    dark = {
      bg0 = p.dark0,
      bg1 = p.dark1,
      bg2 = p.dark2,
      bg3 = p.dark3,
      bg4 = p.dark4,

      fg0 = p.light0,
      fg1 = p.light1,
      fg2 = p.light2,
      fg3 = p.light3,
      fg4 = p.light4,

      red = p.light_red,
      orange = p.light_orange,
      yellow = p.light_yellow,
      green = p.light_green,
      aqua = p.light_aqua,
      blue = p.light_blue,
      purple = p.light_purple,
      fuscia = p.light_fuscia,

      neutral_red = p.neutral_red,
      neutral_yellow = p.neutral_yellow,
      neutral_orange = p.neutral_orange,
      neutral_green = p.neutral_green,
      neutral_aqua = p.neutral_aqua,
      neutral_blue = p.neutral_blue,
      neutral_purple = p.neutral_purple,
      neutral_fuscia = p.neutral_fuscia,

      dark_red = p.dark_red,
      dark_orange = p.dark_orange,
      dark_yellow = p.dark_yellow,
      dark_green = p.dark_green,
      dark_aqua = p.dark_aqua,
      dark_blue = p.dark_blue,
      dark_purple = p.dark_purple,
      dark_fuscia = p.dark_fuscia,

      alt_g = p.alt_g,
      alt_a = p.alt_a,
      alt_b = p.alt_b,
      alt_h = p.alt_h,
      alt_s = p.alt_s,
    },

    light = {
      bg0 = p.light0,
      bg1 = p.light1,
      bg2 = p.light2,
      bg3 = p.light3,
      bg4 = p.light4,

      fg0 = p.dark0,
      fg1 = p.dark1,
      fg2 = p.dark2,
      fg3 = p.dark3,
      fg4 = p.dark4,

      red = p.dark_red,
      orange = p.dark_orange,
      yellow = p.dark_yellow,
      green = p.dark_green,
      aqua = p.dark_aqua,
      blue = p.dark_blue,
      purple = p.dark_purple,
      fuscia = p.dark_fuscia,

      neutral_red = p.neutral_red,
      neutral_orange = p.neutral_orange,
      neutral_yellow = p.neutral_yellow,
      neutral_green = p.neutral_green,
      neutral_aqua = p.neutral_aqua,
      neutral_blue = p.neutral_blue,
      neutral_purple = p.neutral_purple,
      neutral_fuscia = p.neutral_fuscia,

      dark_red = p.light_red,
      dark_orange = p.light_orange,
      dark_yellow = p.light_yellow,
      dark_green = p.light_green,
      dark_aqua = p.light_aqua,
      dark_blue = p.light_blue,
      dark_purple = p.light_purple,
      dark_fuscia = p.light_fuscia,

      alt_g = p.alt_g,
      alt_a = p.alt_a,
      alt_b = p.alt_b,
      alt_h = p.alt_h,
      alt_s = p.alt_s,
    },
  }

  if contrast ~= nil and contrast ~= "" then
    color_groups[bg].bg0 = p[bg .. "0_" .. contrast]
    color_groups[bg].dark_orange = p[bg .. "_orange_" .. contrast]
    color_groups[bg].dark_red = p[bg .. "_red_" .. contrast]
    color_groups[bg].dark_green = p[bg .. "_green_" .. contrast]
    color_groups[bg].dark_yellow = p[bg .. "_yellow_" .. contrast]
    color_groups[bg].dark_blue = p[bg .. "_blue_" .. contrast]
    color_groups[bg].dark_purple = p[bg .. "_purple_" .. contrast]
    color_groups[bg].dark_aqua = p[bg .. "_aqua_" .. contrast]
    color_groups[bg].dark_fuscia = p[bg .. "_fuscia_" .. contrast]
  end

  return color_groups[bg]
end

local function get_groups()
  local colors = get_colors()
  local config = Chocolatier.config

  if config.terminal_colors then
    local term_colors = {
      colors.bg0,
      colors.neutral_red,
      colors.neutral_green,
      colors.neutral_yellow,
      colors.neutral_blue,
      colors.neutral_purple,
      colors.neutral_aqua,
      colors.fg4,
      colors.alt_g,
      colors.red,
      colors.green,
      colors.yellow,
      colors.blue,
      colors.purple,
      colors.aqua,
      colors.fg1,
    }
    for index, value in ipairs(term_colors) do
      vim.g["terminal_color_" .. index - 1] = value
    end
  end

  local groups = {
    ChocolatierFg0 = { fg = colors.fg0 },
    ChocolatierFg1 = { fg = colors.fg1 },
    ChocolatierFg2 = { fg = colors.fg2 },
    ChocolatierFg3 = { fg = colors.fg3 },
    ChocolatierFg4 = { fg = colors.fg4 },
    ChocolatierAltG = { fg = colors.alt_g },
    ChocolatierAltH = { fg = colors.alt_h },
    ChocolatierAltA = { fg = colors.alt_a },
    ChocolatierAltB = { fg = colors.alt_b },
    ChocolatierAltR = { fg = colors.alt_r },
    ChocolatierAltS = { fg = colors.alt_s },
    ChocolatierBg0 = { fg = colors.bg0 },
    ChocolatierBg1 = { fg = colors.bg1 },
    ChocolatierBg2 = { fg = colors.bg2 },
    ChocolatierBg3 = { fg = colors.bg3 },
    ChocolatierBg4 = { fg = colors.bg4 },
    ChocolatierRed = { fg = colors.red },
    ChocolatierRedBold = { fg = colors.red, bold = config.bold },
    ChocolatierOrange = { fg = colors.orange },
    ChocolatierOrangeBold = { fg = colors.orange, bold = config.bold },
    ChocolatierYellow = { fg = colors.yellow },
    ChocolatierYellowBold = { fg = colors.yellow, bold = config.bold },
    ChocolatierGreen = { fg = colors.green },
    ChocolatierGreenBold = { fg = colors.green, bold = config.bold },
    ChocolatierAqua = { fg = colors.aqua },
    ChocolatierAquaBold = { fg = colors.aqua, bold = config.bold },
    ChocolatierBlue = { fg = colors.blue },
    ChocolatierBlueBold = { fg = colors.blue, bold = config.bold },
    ChocolatierPurple = { fg = colors.purple },
    ChocolatierPurpleBold = { fg = colors.purple, bold = config.bold },
    ChocolatierFuscia = { fg = colors.fuscia },
    ChocolatierFusciaBold = { fg = colors.fuscia, bold = config.bold },
    ChocolatierRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
      or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
    ChocolatierOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
      or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
    ChocolatierYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
      or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
    ChocolatierGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
      or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
    ChocolatierAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
      or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
    ChocolatierBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
      or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
    ChocolatierPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
      or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
    ChocolatierFusciaSign = config.transparent_mode and { fg = colors.fuscia, reverse = config.invert_signs }
      or { fg = colors.fuscia, bg = colors.bg1, reverse = config.invert_signs },
    ChocolatierRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    ChocolatierOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
    ChocolatierYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    ChocolatierGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    ChocolatierAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    ChocolatierBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    ChocolatierPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    ChocolatierFusciaUnderline = { undercurl = config.undercurl, sp = colors.fuscia },
    Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    -- TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    -- TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    -- TabLine = { link = "TabLineFill" },
    TabLineFill = { fg = colors.fg2, bg = colors.bg1 },
    TabLineSel = { fg = colors.fg2, bg = colors.bg3 },
    TabLine = { fg = colors.red, bg = colors.blue },
    MatchParen = { bg = colors.bg0, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
    NonText = { link = "ChocolatierBg2" },
    SpecialKey = { link = "ChocolatierFg4" },
    Visual = { bg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "ChocolatierPurple" },
    Underlined = { fg = colors.blue, underline = config.underline },
    -- StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
    -- StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
    StatusLine = { fg = colors.bg2, bg = colors.fg1 },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg4 },
    WinBar = { fg = colors.fg4, bg = colors.bg0 },
    WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
    WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "ChocolatierBlueBold" },
    Title = { link = "ChocolatierFg3" },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MoreMsg = { link = "ChocolatierYellowBold" },
    ModeMsg = { link = "ChocolatierYellowBold" },
    Question = { link = "ChocolatierOrangeBold" },
    WarningMsg = { link = "ChocolatierRedBold" },
    LineNr = { fg = colors.bg4 },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
    Folded = { fg = colors.alt_g, bg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = colors.alt_g, bg = nil } or { fg = colors.alt_g, bg = colors.bg1 },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "ChocolatierOrange" },
    Comment = { fg = colors.alt_g, italic = config.italic.comments },
    Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
    Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
    Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
    Statement = { link = "ChocolatierRed" },
    Conditional = { link = "ChocolatierRed" },
    Repeat = { link = "ChocolatierRed" },
    Label = { link = "ChocolatierRed" },
    Exception = { link = "ChocolatierRed" },
    Operator = { fg = colors.orange, italic = config.italic.operators },
    Keyword = { link = "ChocolatierRed" },
    Identifier = { link = "ChocolatierBlue" },
    Function = { link = "ChocolatierFusciaBold" },
    PreProc = { link = "ChocolatierAqua" },
    Include = { link = "ChocolatierAqua" },
    Define = { link = "ChocolatierAqua" },
    Macro = { link = "ChocolatierAqua" },
    PreCondit = { link = "ChocolatierAqua" },
    Constant = { link = "ChocolatierPurple" },
    Character = { link = "ChocolatierPurple" },
    String = { fg = colors.green, italic = config.italic.strings },
    Boolean = { link = "ChocolatierPurple" },
    Number = { link = "ChocolatierPurple" },
    Float = { link = "ChocolatierPurple" },
    Type = { link = "ChocolatierYellow" },
    StorageClass = { link = "ChocolatierOrange" },
    Structure = { link = "ChocolatierAqua" },
    Typedef = { link = "ChocolatierYellow" },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    DiffDelete = { bg = colors.dark_red },
    DiffAdd = { bg = colors.dark_green },
    DiffChange = { bg = colors.dark_aqua },
    DiffText = { bg = colors.yellow, fg = colors.bg0 },
    SpellCap = { link = "ChocolatierBlueUnderline" },
    SpellBad = { link = "ChocolatierRedUnderline" },
    SpellLocal = { link = "ChocolatierAquaUnderline" },
    SpellRare = { link = "ChocolatierPurpleUnderline" },
    Whitespace = { fg = colors.bg2 },
    Delimiter = { link = "ChocolatierOrange" },
    EndOfBuffer = { link = "NonText" },
    DiagnosticError = { link = "ChocolatierRed" },
    DiagnosticSignError = { link = "ChocolatierRedSign" },
    DiagnosticUnderlineError = { link = "ChocolatierRedUnderline" },
    DiagnosticWarn = { link = "ChocolatierYellow" },
    DiagnosticSignWarn = { link = "ChocolatierYellowSign" },
    DiagnosticUnderlineWarn = { link = "ChocolatierYellowUnderline" },
    DiagnosticInfo = { link = "ChocolatierBlue" },
    DiagnosticSignInfo = { link = "ChocolatierBlueSign" },
    DiagnosticUnderlineInfo = { link = "ChocolatierBlueUnderline" },
    DiagnosticHint = { link = "ChocolatierAqua" },
    DiagnosticSignHint = { link = "ChocolatierAquaSign" },
    DiagnosticUnderlineHint = { link = "ChocolatierAquaUnderline" },
    DiagnosticFloatingError = { link = "ChocolatierRed" },
    DiagnosticFloatingWarn = { link = "ChocolatierOrange" },
    DiagnosticFloatingInfo = { link = "ChocolatierBlue" },
    DiagnosticFloatingHint = { link = "ChocolatierAqua" },
    DiagnosticVirtualTextError = { link = "ChocolatierRed" },
    DiagnosticVirtualTextWarn = { link = "ChocolatierYellow" },
    DiagnosticVirtualTextInfo = { link = "ChocolatierBlue" },
    DiagnosticVirtualTextHint = { link = "ChocolatierAqua" },
    DiagnosticOk = { link = "ChocolatierGreenSign" },
    LspReferenceRead = { link = "ChocolatierYellowBold" },
    LspReferenceText = { link = "ChocolatierYellowBold" },
    LspReferenceWrite = { link = "ChocolatierOrangeBold" },
    LspCodeLens = { link = "ChocolatierAltG" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { link = "ChocolatierGreen" },
    gitcommitDiscardedFile = { link = "ChocolatierRed" },
    GitSignsAdd = { link = "ChocolatierGreen" },
    GitSignsChange = { link = "ChocolatierAqua" },
    GitSignsDelete = { link = "ChocolatierRed" },
    NvimTreeSymlink = { fg = colors.neutral_aqua },
    NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
    NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
    NvimTreeFileIcon = { fg = colors.light2 },
    NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
    NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
    NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = colors.neutral_purple },
    NvimTreeIndentMarker = { fg = colors.dark3 },
    NvimTreeGitDirty = { fg = colors.neutral_yellow },
    NvimTreeGitStaged = { fg = colors.neutral_yellow },
    NvimTreeGitMerge = { fg = colors.neutral_purple },
    NvimTreeGitRenamed = { fg = colors.neutral_purple },
    NvimTreeGitNew = { fg = colors.neutral_yellow },
    NvimTreeGitDeleted = { fg = colors.neutral_red },
    NvimTreeWindowPicker = { bg = colors.aqua },
    debugPC = { link = "DiffAdd" },
    debugBreakpoint = { link = "ChocolatierRedSign" },
    StartifyBracket = { link = "ChocolatierFg3" },
    StartifyFile = { link = "ChocolatierFg1" },
    StartifyNumber = { link = "ChocolatierBlue" },
    StartifyPath = { link = "ChocolatierAltG" },
    StartifySlash = { link = "ChocolatierAltG" },
    StartifySection = { link = "ChocolatierYellow" },
    StartifySpecial = { link = "ChocolatierBg2" },
    StartifyHeader = { link = "ChocolatierOrange" },
    StartifyFooter = { link = "ChocolatierBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "ChocolatierAqua" },
    DirvishArg = { link = "ChocolatierYellow" },
    netrwDir = { link = "ChocolatierAqua" },
    netrwClassify = { link = "ChocolatierAqua" },
    netrwLink = { link = "ChocolatierAltG" },
    netrwSymLink = { link = "ChocolatierFg1" },
    netrwExe = { link = "ChocolatierYellow" },
    netrwComment = { link = "ChocolatierAltG" },
    netrwList = { link = "ChocolatierBlue" },
    netrwHelpCmd = { link = "ChocolatierAqua" },
    netrwCmdSep = { link = "ChocolatierFg3" },
    netrwVersion = { link = "ChocolatierGreen" },
    NERDTreeDir = { link = "ChocolatierAqua" },
    NERDTreeDirSlash = { link = "ChocolatierAqua" },
    NERDTreeOpenable = { link = "ChocolatierOrange" },
    NERDTreeClosable = { link = "ChocolatierOrange" },
    NERDTreeFile = { link = "ChocolatierFg1" },
    NERDTreeExecFile = { link = "ChocolatierYellow" },
    NERDTreeUp = { link = "ChocolatierAltG" },
    NERDTreeCWD = { link = "ChocolatierGreen" },
    NERDTreeHelp = { link = "ChocolatierFg1" },
    NERDTreeToggleOn = { link = "ChocolatierGreen" },
    NERDTreeToggleOff = { link = "ChocolatierRed" },
    CocErrorSign = { link = "ChocolatierRedSign" },
    CocWarningSign = { link = "ChocolatierOrangeSign" },
    CocInfoSign = { link = "ChocolatierBlueSign" },
    CocHintSign = { link = "ChocolatierAquaSign" },
    CocErrorFloat = { link = "ChocolatierRed" },
    CocWarningFloat = { link = "ChocolatierOrange" },
    CocInfoFloat = { link = "ChocolatierBlue" },
    CocHintFloat = { link = "ChocolatierAqua" },
    CocDiagnosticsError = { link = "ChocolatierRed" },
    CocDiagnosticsWarning = { link = "ChocolatierOrange" },
    CocDiagnosticsInfo = { link = "ChocolatierBlue" },
    CocDiagnosticsHint = { link = "ChocolatierAqua" },
    CocSelectedText = { link = "ChocolatierRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "ChocolatierAltG" },
    CocErrorHighlight = { link = "ChocolatierRedUnderline" },
    CocWarningHighlight = { link = "ChocolatierOrangeUnderline" },
    CocInfoHighlight = { link = "ChocolatierBlueUnderline" },
    CocHintHighlight = { link = "ChocolatierAquaUnderline" },
    TelescopeNormal = { link = "ChocolatierFg1" },
    TelescopeSelection = { link = "ChocolatierOrangeBold" },
    TelescopeSelectionCaret = { link = "ChocolatierRed" },
    TelescopeMultiSelection = { link = "ChocolatierAltG" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "ChocolatierBlue" },
    TelescopePromptPrefix = { link = "ChocolatierRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    CmpItemAbbr = { link = "ChocolatierFg0" },
    CmpItemAbbrDeprecated = { link = "ChocolatierFg1" },
    CmpItemAbbrMatch = { link = "ChocolatierBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "ChocolatierBlueUnderline" },
    CmpItemMenu = { link = "ChocolatierAltG" },
    CmpItemKindText = { link = "ChocolatierOrange" },
    CmpItemKindVariable = { link = "ChocolatierOrange" },
    CmpItemKindMethod = { link = "ChocolatierBlue" },
    CmpItemKindFunction = { link = "ChocolatierBlue" },
    CmpItemKindConstructor = { link = "ChocolatierYellow" },
    CmpItemKindUnit = { link = "ChocolatierBlue" },
    CmpItemKindField = { link = "ChocolatierBlue" },
    CmpItemKindClass = { link = "ChocolatierYellow" },
    CmpItemKindInterface = { link = "ChocolatierYellow" },
    CmpItemKindModule = { link = "ChocolatierBlue" },
    CmpItemKindProperty = { link = "ChocolatierBlue" },
    CmpItemKindValue = { link = "ChocolatierOrange" },
    CmpItemKindEnum = { link = "ChocolatierYellow" },
    CmpItemKindOperator = { link = "ChocolatierYellow" },
    CmpItemKindKeyword = { link = "ChocolatierPurple" },
    CmpItemKindEvent = { link = "ChocolatierPurple" },
    CmpItemKindReference = { link = "ChocolatierPurple" },
    CmpItemKindColor = { link = "ChocolatierPurple" },
    CmpItemKindSnippet = { link = "ChocolatierGreen" },
    CmpItemKindFile = { link = "ChocolatierBlue" },
    CmpItemKindFolder = { link = "ChocolatierBlue" },
    CmpItemKindEnumMember = { link = "ChocolatierAqua" },
    CmpItemKindConstant = { link = "ChocolatierOrange" },
    CmpItemKindStruct = { link = "ChocolatierYellow" },
    CmpItemKindTypeParameter = { link = "ChocolatierYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "ChocolatierOrange" },
    diffNewFile = { link = "ChocolatierYellow" },
    diffOldFile = { link = "ChocolatierOrange" },
    diffLine = { link = "ChocolatierBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "ChocolatierBlue" },
    NavicIconsModule = { link = "ChocolatierOrange" },
    NavicIconsNamespace = { link = "ChocolatierBlue" },
    NavicIconsPackage = { link = "ChocolatierAqua" },
    NavicIconsClass = { link = "ChocolatierYellow" },
    NavicIconsMethod = { link = "ChocolatierBlue" },
    NavicIconsProperty = { link = "ChocolatierAqua" },
    NavicIconsField = { link = "ChocolatierPurple" },
    NavicIconsConstructor = { link = "ChocolatierBlue" },
    NavicIconsEnum = { link = "ChocolatierPurple" },
    NavicIconsInterface = { link = "ChocolatierGreen" },
    NavicIconsFunction = { link = "ChocolatierBlue" },
    NavicIconsVariable = { link = "ChocolatierPurple" },
    NavicIconsConstant = { link = "ChocolatierOrange" },
    NavicIconsString = { link = "ChocolatierGreen" },
    NavicIconsNumber = { link = "ChocolatierOrange" },
    NavicIconsBoolean = { link = "ChocolatierOrange" },
    NavicIconsArray = { link = "ChocolatierOrange" },
    NavicIconsObject = { link = "ChocolatierOrange" },
    NavicIconsKey = { link = "ChocolatierAqua" },
    NavicIconsNull = { link = "ChocolatierOrange" },
    NavicIconsEnumMember = { link = "ChocolatierYellow" },
    NavicIconsStruct = { link = "ChocolatierPurple" },
    NavicIconsEvent = { link = "ChocolatierYellow" },
    NavicIconsOperator = { link = "ChocolatierRed" },
    NavicIconsTypeParameter = { link = "ChocolatierRed" },
    NavicText = { link = "ChocolatierWhite" },
    NavicSeparator = { link = "ChocolatierWhite" },
    htmlTag = { link = "ChocolatierAquaBold" },
    htmlEndTag = { link = "ChocolatierAquaBold" },
    htmlTagName = { link = "ChocolatierBlue" },
    htmlArg = { link = "ChocolatierOrange" },
    htmlTagN = { link = "ChocolatierFg1" },
    htmlSpecialTagName = { link = "ChocolatierBlue" },
    htmlLink = { fg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "ChocolatierRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    xmlTag = { link = "ChocolatierAquaBold" },
    xmlEndTag = { link = "ChocolatierAquaBold" },
    xmlTagName = { link = "ChocolatierBlue" },
    xmlEqual = { link = "ChocolatierBlue" },
    docbkKeyword = { link = "ChocolatierAquaBold" },
    xmlDocTypeDecl = { link = "ChocolatierAltG" },
    xmlDocTypeKeyword = { link = "ChocolatierPurple" },
    xmlCdataStart = { link = "ChocolatierAltG" },
    xmlCdataCdata = { link = "ChocolatierPurple" },
    dtdFunction = { link = "ChocolatierAltG" },
    dtdTagName = { link = "ChocolatierPurple" },
    xmlAttrib = { link = "ChocolatierOrange" },
    xmlProcessingDelim = { link = "ChocolatierAltG" },
    dtdParamEntityPunct = { link = "ChocolatierAltG" },
    dtdParamEntityDPunct = { link = "ChocolatierAltG" },
    xmlAttribPunct = { link = "ChocolatierAltG" },
    xmlEntity = { link = "ChocolatierRed" },
    xmlEntityPunct = { link = "ChocolatierRed" },
    clojureKeyword = { link = "ChocolatierBlue" },
    clojureCond = { link = "ChocolatierOrange" },
    clojureSpecial = { link = "ChocolatierOrange" },
    clojureDefine = { link = "ChocolatierOrange" },
    clojureFunc = { link = "ChocolatierYellow" },
    clojureRepeat = { link = "ChocolatierYellow" },
    clojureCharacter = { link = "ChocolatierAqua" },
    clojureStringEscape = { link = "ChocolatierAqua" },
    clojureException = { link = "ChocolatierRed" },
    clojureRegexp = { link = "ChocolatierAqua" },
    clojureRegexpEscape = { link = "ChocolatierAqua" },
    clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "ChocolatierFg3" },
    clojureAnonArg = { link = "ChocolatierYellow" },
    clojureVariable = { link = "ChocolatierBlue" },
    clojureMacro = { link = "ChocolatierOrange" },
    clojureMeta = { link = "ChocolatierYellow" },
    clojureDeref = { link = "ChocolatierYellow" },
    clojureQuote = { link = "ChocolatierYellow" },
    clojureUnquote = { link = "ChocolatierYellow" },
    cOperator = { link = "ChocolatierPurple" },
    cppOperator = { link = "ChocolatierPurple" },
    cStructure = { link = "ChocolatierOrange" },
    pythonBuiltin = { link = "ChocolatierOrange" },
    pythonBuiltinObj = { link = "ChocolatierOrange" },
    pythonBuiltinFunc = { link = "ChocolatierOrange" },
    pythonFunction = { link = "ChocolatierAqua" },
    pythonDecorator = { link = "ChocolatierRed" },
    pythonInclude = { link = "ChocolatierBlue" },
    pythonImport = { link = "ChocolatierBlue" },
    pythonRun = { link = "ChocolatierBlue" },
    pythonCoding = { link = "ChocolatierBlue" },
    pythonOperator = { link = "ChocolatierRed" },
    pythonException = { link = "ChocolatierRed" },
    pythonExceptions = { link = "ChocolatierPurple" },
    pythonBoolean = { link = "ChocolatierPurple" },
    pythonDot = { link = "ChocolatierFg3" },
    pythonConditional = { link = "ChocolatierRed" },
    pythonRepeat = { link = "ChocolatierRed" },
    pythonDottedName = { link = "ChocolatierGreenBold" },
    cssBraces = { link = "ChocolatierBlue" },
    cssFunctionName = { link = "ChocolatierYellow" },
    cssIdentifier = { link = "ChocolatierOrange" },
    cssClassName = { link = "ChocolatierGreen" },
    cssColor = { link = "ChocolatierBlue" },
    cssSelectorOp = { link = "ChocolatierBlue" },
    cssSelectorOp2 = { link = "ChocolatierBlue" },
    cssImportant = { link = "ChocolatierGreen" },
    cssVendor = { link = "ChocolatierFg1" },
    cssTextProp = { link = "ChocolatierAqua" },
    cssAnimationProp = { link = "ChocolatierAqua" },
    cssUIProp = { link = "ChocolatierYellow" },
    cssTransformProp = { link = "ChocolatierAqua" },
    cssTransitionProp = { link = "ChocolatierAqua" },
    cssPrintProp = { link = "ChocolatierAqua" },
    cssPositioningProp = { link = "ChocolatierYellow" },
    cssBoxProp = { link = "ChocolatierAqua" },
    cssFontDescriptorProp = { link = "ChocolatierAqua" },
    cssFlexibleBoxProp = { link = "ChocolatierAqua" },
    cssBorderOutlineProp = { link = "ChocolatierAqua" },
    cssBackgroundProp = { link = "ChocolatierAqua" },
    cssMarginProp = { link = "ChocolatierAqua" },
    cssListProp = { link = "ChocolatierAqua" },
    cssTableProp = { link = "ChocolatierAqua" },
    cssFontProp = { link = "ChocolatierAqua" },
    cssPaddingProp = { link = "ChocolatierAqua" },
    cssDimensionProp = { link = "ChocolatierAqua" },
    cssRenderProp = { link = "ChocolatierAqua" },
    cssColorProp = { link = "ChocolatierAqua" },
    cssGeneratedContentProp = { link = "ChocolatierAqua" },
    javaScriptBraces = { link = "ChocolatierFg1" },
    javaScriptFunction = { link = "ChocolatierAqua" },
    javaScriptIdentifier = { link = "ChocolatierRed" },
    javaScriptMember = { link = "ChocolatierBlue" },
    javaScriptNumber = { link = "ChocolatierPurple" },
    javaScriptNull = { link = "ChocolatierPurple" },
    javaScriptParens = { link = "ChocolatierFg3" },
    typescriptReserved = { link = "ChocolatierAqua" },
    typescriptLabel = { link = "ChocolatierAqua" },
    typescriptFuncKeyword = { link = "ChocolatierAqua" },
    typescriptIdentifier = { link = "ChocolatierOrange" },
    typescriptBraces = { link = "ChocolatierFg1" },
    typescriptEndColons = { link = "ChocolatierFg1" },
    typescriptDOMObjects = { link = "ChocolatierFg1" },
    typescriptAjaxMethods = { link = "ChocolatierFg1" },
    typescriptLogicSymbols = { link = "ChocolatierFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "ChocolatierFg1" },
    typescriptParens = { link = "ChocolatierFg3" },
    typescriptOpSymbols = { link = "ChocolatierFg3" },
    typescriptHtmlElemProperties = { link = "ChocolatierFg1" },
    typescriptNull = { link = "ChocolatierPurple" },
    typescriptInterpolationDelimiter = { link = "ChocolatierAqua" },
    purescriptModuleKeyword = { link = "ChocolatierAqua" },
    purescriptModuleName = { link = "ChocolatierFg1" },
    purescriptWhere = { link = "ChocolatierAqua" },
    purescriptDelimiter = { link = "ChocolatierFg4" },
    purescriptType = { link = "ChocolatierFg1" },
    purescriptImportKeyword = { link = "ChocolatierAqua" },
    purescriptHidingKeyword = { link = "ChocolatierAqua" },
    purescriptAsKeyword = { link = "ChocolatierAqua" },
    purescriptStructure = { link = "ChocolatierAqua" },
    purescriptOperator = { link = "ChocolatierBlue" },
    purescriptTypeVar = { link = "ChocolatierFg1" },
    purescriptConstructor = { link = "ChocolatierFg1" },
    purescriptFunction = { link = "ChocolatierFg1" },
    purescriptConditional = { link = "ChocolatierOrange" },
    purescriptBacktick = { link = "ChocolatierOrange" },
    coffeeExtendedOp = { link = "ChocolatierFg3" },
    coffeeSpecialOp = { link = "ChocolatierFg3" },
    coffeeCurly = { link = "ChocolatierOrange" },
    coffeeParen = { link = "ChocolatierFg3" },
    coffeeBracket = { link = "ChocolatierOrange" },
    rubyStringDelimiter = { link = "ChocolatierGreen" },
    rubyInterpolationDelimiter = { link = "ChocolatierAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "ChocolatierRed" },
    objcDirective = { link = "ChocolatierBlue" },
    goDirective = { link = "ChocolatierAqua" },
    goConstants = { link = "ChocolatierPurple" },
    goDeclaration = { link = "ChocolatierRed" },
    goDeclType = { link = "ChocolatierBlue" },
    goBuiltins = { link = "ChocolatierOrange" },
    luaIn = { link = "ChocolatierRed" },
    luaFunction = { link = "ChocolatierAqua" },
    luaTable = { link = "ChocolatierOrange" },
    moonSpecialOp = { link = "ChocolatierFg3" },
    moonExtendedOp = { link = "ChocolatierFg3" },
    moonFunction = { link = "ChocolatierFg3" },
    moonObject = { link = "ChocolatierYellow" },
    javaAnnotation = { link = "ChocolatierBlue" },
    javaDocTags = { link = "ChocolatierAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "ChocolatierFg3" },
    javaParen1 = { link = "ChocolatierFg3" },
    javaParen2 = { link = "ChocolatierFg3" },
    javaParen3 = { link = "ChocolatierFg3" },
    javaParen4 = { link = "ChocolatierFg3" },
    javaParen5 = { link = "ChocolatierFg3" },
    javaOperator = { link = "ChocolatierOrange" },
    javaVarArg = { link = "ChocolatierGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "ChocolatierGreen" },
    elixirInterpolationDelimiter = { link = "ChocolatierAqua" },
    elixirModuleDeclaration = { link = "ChocolatierYellow" },
    scalaNameDefinition = { link = "ChocolatierFg1" },
    scalaCaseFollowing = { link = "ChocolatierFg1" },
    scalaCapitalWord = { link = "ChocolatierFg1" },
    scalaTypeExtension = { link = "ChocolatierFg1" },
    scalaKeyword = { link = "ChocolatierRed" },
    scalaKeywordModifier = { link = "ChocolatierRed" },
    scalaSpecial = { link = "ChocolatierAqua" },
    scalaOperator = { link = "ChocolatierFg1" },
    scalaTypeDeclaration = { link = "ChocolatierYellow" },
    scalaTypeTypePostDeclaration = { link = "ChocolatierYellow" },
    scalaInstanceDeclaration = { link = "ChocolatierFg1" },
    scalaInterpolation = { link = "ChocolatierAqua" },
    markdownItalic = { fg = colors.fg3, italic = true },
    markdownBold = { fg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
    markdownH1 = { link = "ChocolatierGreenBold" },
    markdownH2 = { link = "ChocolatierGreenBold" },
    markdownH3 = { link = "ChocolatierYellowBold" },
    markdownH4 = { link = "ChocolatierYellowBold" },
    markdownH5 = { link = "ChocolatierYellow" },
    markdownH6 = { link = "ChocolatierYellow" },
    markdownCode = { link = "ChocolatierAqua" },
    markdownCodeBlock = { link = "ChocolatierAqua" },
    markdownCodeDelimiter = { link = "ChocolatierAqua" },
    markdownBlockquote = { link = "ChocolatierAltG" },
    markdownListMarker = { link = "ChocolatierAltG" },
    markdownOrderedListMarker = { link = "ChocolatierAltG" },
    markdownRule = { link = "ChocolatierAltG" },
    markdownHeadingRule = { link = "ChocolatierAltG" },
    markdownUrlDelimiter = { link = "ChocolatierFg3" },
    markdownLinkDelimiter = { link = "ChocolatierFg3" },
    markdownLinkTextDelimiter = { link = "ChocolatierFg3" },
    markdownHeadingDelimiter = { link = "ChocolatierOrange" },
    markdownUrl = { link = "ChocolatierPurple" },
    markdownUrlTitleDelimiter = { link = "ChocolatierGreen" },
    markdownLinkText = { fg = colors.alt_g, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "ChocolatierBlue" },
    haskellIdentifier = { link = "ChocolatierAqua" },
    haskellSeparator = { link = "ChocolatierFg4" },
    haskellDelimiter = { link = "ChocolatierOrange" },
    haskellOperators = { link = "ChocolatierPurple" },
    haskellBacktick = { link = "ChocolatierOrange" },
    haskellStatement = { link = "ChocolatierPurple" },
    haskellConditional = { link = "ChocolatierPurple" },
    haskellLet = { link = "ChocolatierRed" },
    haskellDefault = { link = "ChocolatierRed" },
    haskellWhere = { link = "ChocolatierRed" },
    haskellBottom = { link = "ChocolatierRedBold" },
    haskellImportKeywords = { link = "ChocolatierPurpleBold" },
    haskellDeclKeyword = { link = "ChocolatierOrange" },
    haskellDecl = { link = "ChocolatierOrange" },
    haskellDeriving = { link = "ChocolatierPurple" },
    haskellAssocType = { link = "ChocolatierAqua" },
    haskellNumber = { link = "ChocolatierAqua" },
    haskellPragma = { link = "ChocolatierRedBold" },
    haskellTH = { link = "ChocolatierAquaBold" },
    haskellForeignKeywords = { link = "ChocolatierGreen" },
    haskellKeyword = { link = "ChocolatierRed" },
    haskellFloat = { link = "ChocolatierAqua" },
    haskellInfix = { link = "ChocolatierPurple" },
    haskellQuote = { link = "ChocolatierGreenBold" },
    haskellShebang = { link = "ChocolatierYellowBold" },
    haskellLiquid = { link = "ChocolatierPurpleBold" },
    haskellQuasiQuoted = { link = "ChocolatierBlueBold" },
    haskellRecursiveDo = { link = "ChocolatierPurple" },
    haskellQuotedType = { link = "ChocolatierRed" },
    haskellPreProc = { link = "ChocolatierFg4" },
    haskellTypeRoles = { link = "ChocolatierRedBold" },
    haskellTypeForall = { link = "ChocolatierRed" },
    haskellPatternKeyword = { link = "ChocolatierBlue" },
    jsonKeyword = { link = "ChocolatierGreen" },
    jsonQuote = { link = "ChocolatierGreen" },
    jsonBraces = { link = "ChocolatierFg1" },
    jsonString = { link = "ChocolatierFg1" },
    mailQuoted1 = { link = "ChocolatierAqua" },
    mailQuoted2 = { link = "ChocolatierPurple" },
    mailQuoted3 = { link = "ChocolatierYellow" },
    mailQuoted4 = { link = "ChocolatierGreen" },
    mailQuoted5 = { link = "ChocolatierRed" },
    mailQuoted6 = { link = "ChocolatierOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "ChocolatierFg1" },
    csEndColon = { link = "ChocolatierFg1" },
    csLogicSymbols = { link = "ChocolatierFg1" },
    csParens = { link = "ChocolatierFg3" },
    csOpSymbols = { link = "ChocolatierFg3" },
    csInterpolationDelimiter = { link = "ChocolatierFg3" },
    csInterpolationAlignDel = { link = "ChocolatierAquaBold" },
    csInterpolationFormat = { link = "ChocolatierAqua" },
    csInterpolationFormatDel = { link = "ChocolatierAquaBold" },
    rustSigil = { link = "ChocolatierOrange" },
    rustEscape = { link = "ChocolatierAqua" },
    rustStringContinuation = { link = "ChocolatierAqua" },
    rustEnum = { link = "ChocolatierAqua" },
    rustStructure = { link = "ChocolatierAqua" },
    rustModPathSep = { link = "ChocolatierFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "ChocolatierAqua" },
    ocamlOperator = { link = "ChocolatierFg1" },
    ocamlKeyChar = { link = "ChocolatierOrange" },
    ocamlArrow = { link = "ChocolatierOrange" },
    ocamlInfixOpKeyword = { link = "ChocolatierRed" },
    ocamlConstructor = { link = "ChocolatierOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "ChocolatierFg1" },
    LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "ChocolatierFg1" },
    LspSagaAutoPreview = { link = "ChocolatierOrange" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "ChocolatierAqua" },
    LspSagaDefPreviewBorder = { link = "ChocolatierBlue" },
    LspSagaHoverBorder = { link = "ChocolatierOrange" },
    LspSagaRenameBorder = { link = "ChocolatierBlue" },
    LspSagaDiagnosticSource = { link = "ChocolatierOrange" },
    LspSagaDiagnosticBorder = { link = "ChocolatierPurple" },
    LspSagaDiagnosticHeader = { link = "ChocolatierGreen" },
    LspSagaSignatureHelpBorder = { link = "ChocolatierGreen" },
    SagaShadow = { link = "ChocolatierBg0" },
    DashboardShortCut = { link = "ChocolatierOrange" },
    DashboardHeader = { link = "ChocolatierAqua" },
    DashboardCenter = { link = "ChocolatierYellow" },
    DashboardFooter = { fg = colors.purple, italic = true },
    MasonHighlight = { link = "ChocolatierAqua" },
    MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
    MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
    MasonHighlightSecondary = { fg = colors.yellow },
    MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
    MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = colors.fg4 },
    MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
    MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "ChocolatierFg1" },
    CarbonExe = { link = "ChocolatierYellow" },
    CarbonSymlink = { link = "ChocolatierAqua" },
    CarbonBrokenSymlink = { link = "ChocolatierRed" },
    CarbonIndicator = { link = "ChocolatierAltG" },
    CarbonDanger = { link = "ChocolatierRed" },
    CarbonPending = { link = "ChocolatierYellow" },
    NoiceCursor = { link = "TermCursor" },
    NotifyDEBUGBorder = { link = "ChocolatierBlue" },
    NotifyDEBUGIcon = { link = "ChocolatierBlue" },
    NotifyDEBUGTitle = { link = "ChocolatierBlue" },
    NotifyERRORBorder = { link = "ChocolatierRed" },
    NotifyERRORIcon = { link = "ChocolatierRed" },
    NotifyERRORTitle = { link = "ChocolatierRed" },
    NotifyINFOBorder = { link = "ChocolatierAqua" },
    NotifyINFOIcon = { link = "ChocolatierAqua" },
    NotifyINFOTitle = { link = "ChocolatierAqua" },
    NotifyTRACEBorder = { link = "ChocolatierGreen" },
    NotifyTRACEIcon = { link = "ChocolatierGreen" },
    NotifyTRACETitle = { link = "ChocolatierGreen" },
    NotifyWARNBorder = { link = "ChocolatierYellow" },
    NotifyWARNIcon = { link = "ChocolatierYellow" },
    NotifyWARNTitle = { link = "ChocolatierYellow" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { fg = colors.red },
    TSRainbowOrange = { fg = colors.orange },
    TSRainbowYellow = { fg = colors.yellow },
    TSRainbowGreen = { fg = colors.green },
    TSRainbowBlue = { fg = colors.blue },
    TSRainbowViolet = { fg = colors.purple },
    TSRainbowCyan = { fg = colors.aqua },
    RainbowDelimiterRed = { fg = colors.red },
    RainbowDelimiterOrange = { fg = colors.orange },
    RainbowDelimiterYellow = { fg = colors.yellow },
    RainbowDelimiterGreen = { fg = colors.green },
    RainbowDelimiterBlue = { fg = colors.blue },
    RainbowDelimiterViolet = { fg = colors.purple },
    RainbowDelimiterCyan = { fg = colors.aqua },
    DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
    DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { link = "ChocolatierYellow" },
    DapUIBreakpointsDisabledLine = { link = "ChocolatierAltG" },
    DapUIBreakpointsInfo = { link = "ChocolatierAqua" },
    DapUIBreakpointsLine = { link = "ChocolatierYellow" },
    DapUIBreakpointsPath = { link = "ChocolatierBlue" },
    DapUICurrentFrameName = { link = "ChocolatierPurple" },
    DapUIDecoration = { link = "ChocolatierPurple" },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { link = "ChocolatierAqua" },
    DapUILineNumber = { link = "ChocolatierYellow" },
    DapUIModifiedValue = { link = "ChocolatierRed" },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { link = "ChocolatierBlue" },
    DapUISource = { link = "ChocolatierFg1" },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    DapUIStoppedThread = { link = "ChocolatierBlue" },
    DapUIThread = { link = "ChocolatierBlue" },
    DapUIType = { link = "ChocolatierOrange" },
    DapUIUnavailable = { link = "ChocolatierAltG" },
    DapUIWatchesEmpty = { link = "ChocolatierAltG" },
    DapUIWatchesError = { link = "ChocolatierRed" },
    DapUIWatchesValue = { link = "ChocolatierYellow" },
    DapUIWinSelect = { link = "ChocolatierYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "ChocolatierGreenBold" },
    DiffviewFilePanelInsertions = { link = "ChocolatierGreenBold" },
    DiffviewFilePanelDeletions = { link = "ChocolatierRedBold" },
    -- TermCursorNC = { link = "WinBar" },
    ["@fill"] = { link = "ChocolatierRed" },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "ChocolatierRed" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "ChocolatierFg1" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@markup"] = { link = "ChocolatierFg1" },
    ["@markup.strong"] = { bold = config.bold },
    ["@markup.italic"] = { link = "@text.emphasis" },
    ["@markup.underline"] = { underline = config.underline },
    ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { link = "ChocolatierGreen" },
    ["@markup.list.unchecked"] = { link = "ChocolatierAltG" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@module"] = { link = "ChocolatierFg1" },
    ["@namespace"] = { link = "ChocolatierFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "ChocolatierFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "ChocolatierGreen" },
    ["@text.todo.unchecked"] = { link = "ChocolatierAltG" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@org.headline.level1"] = { link = "ChocolatierGreen" },
    ["@org.headline.level2"] = { link = "ChocolatierPurple" },
    ["@org.headline.level3"] = { link = "ChocolatierFuscia" },
    ["@org.headline.level4"] = { link = "ChocolatierBlue" },
    ["@org.headline.level5"] = { link = "ChocolatierAqua" },
    ["@org.headline.level6"] = { link = "ChocolatierRed" },
    ["@org.headline.level7"] = { link = "ChocolatierOrange" },
    ["@org.headline.level8"] = { link = "ChocolatierYellow" },
  }

  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

---@param config ChocolatierConfig?
Chocolatier.setup = function(config)
  Chocolatier.config = vim.tbl_deep_extend("force", Chocolatier.config, config or {})
end

--- main load function
Chocolatier.load = function()
  if vim.version().minor < 8 then
    vim.notify_once("chocolatier.nvim: you must use neovim 0.8 or higher")
    return
  end

  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "chocolatier"
  vim.o.termguicolors = true

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Chocolatier
